from __future__ import annotations

from collections.abc import Sequence
from typing import Any


SUPPORTED_PLANT_PREVIEW_CATEGORIES: frozenset[str] = frozenset(
    {
        "company_handoff_request",
        "plant_supported_design_review",
    }
)

STABLE_PREVIEW_CONTRACT_KEYS: tuple[str, ...] = (
    "scope_category",
    "preview_status",
    "allowed_outputs",
    "blocked_outputs",
    "boundary_statements",
    "parsed_intent_rows",
    "persistent",
)

ROUTER_BOUNDARY_APPEND: tuple[str, ...] = (
    "The router records scope only; it does not call an AI service or choose biological components.",
    "Manual review is required before any company-facing draft is used for decision support.",
    "Operational, final-design, ranking, and performance-claim outputs stay blocked.",
)

HANDOFF_BOUNDARY_LABELS: tuple[str, ...] = (
    "not an experimental protocol",
    "not a final construct design",
    "manual expert review required",
)

HANDOFF_BOUNDARY_SECTION_STATEMENTS: tuple[str, ...] = (
    "This draft is not an experimental protocol.",
    "This draft is not a final construct design.",
    "Manual expert review required.",
)

ALLOWED_OUTPUT_BOUNDARY_DOCUMENTATION = "visible only as documentation draft context"
ALLOWED_OUTPUT_BOUNDARY_CONCEPTUAL = "visible only as bounded conceptual context"
BLOCKED_OUTPUT_BOUNDARY = "blocked; not generated by this read-only preview"

PREVIEW_STATUS_BY_CATEGORY: dict[str, str] = {
    "non_plant_out_of_scope": "non-plant input routed out",
    "blocked_wet_lab_execution": "blocked input",
    "blocked_final_sequence_or_primer": "blocked input",
    "mixed_scope_needs_routing": "mixed input; safe fields only",
    "company_handoff_request": "supported plant mock preview",
    "plant_supported_design_review": "supported plant mock preview",
    "safe_conceptual_explanation": "conceptual-only preview",
}


def text(value: Any, fallback: str = "") -> str:
    clean = str(value or "").strip()
    return clean if clean else fallback


def status_label(value: Any, fallback: str = "not recorded") -> str:
    return text(value, fallback).replace("_", " ")


def sequence(value: Any) -> list[Any]:
    if isinstance(value, Sequence) and not isinstance(value, (str, bytes, bytearray)):
        return list(value)
    return []


def preview_status(scope_category: Any) -> str:
    clean = text(scope_category, "safe_conceptual_explanation")
    return PREVIEW_STATUS_BY_CATEGORY.get(clean, "conceptual-only preview")


def allowed_output_boundary(scope_category: Any) -> str:
    clean = text(scope_category, "safe_conceptual_explanation")
    if clean in {
        "non_plant_out_of_scope",
        "blocked_wet_lab_execution",
        "blocked_final_sequence_or_primer",
    }:
        return ALLOWED_OUTPUT_BOUNDARY_CONCEPTUAL
    return ALLOWED_OUTPUT_BOUNDARY_DOCUMENTATION


def output_rows(values: Sequence[Any], boundary: str) -> list[dict[str, str]]:
    return [{"Output": status_label(value), "Preview boundary": boundary} for value in values if text(value)]


def boundary_statement_rows(statements: Sequence[Any]) -> list[dict[str, str]]:
    return [{"Boundary statement": statement} for statement in normalize_boundary_statements(statements)]


def normalize_boundary_statement(value: Any) -> str:
    clean = text(value)
    clean = clean.replace("final sequence", "completed sequence content")
    clean = clean.replace("wet-lab steps", "operational method content")
    clean = clean.replace("wet-lab step", "operational method content")
    return clean


def normalize_boundary_statements(*groups: Any) -> list[str]:
    rows: list[str] = []
    seen: set[str] = set()
    for group in groups:
        items = [group] if isinstance(group, str) else sequence(group)
        for item in items:
            clean = normalize_boundary_statement(item)
            key = clean.casefold()
            if clean and key not in seen:
                seen.add(key)
                rows.append(clean)
    return rows
