# -*- coding: utf-8 -*-
from __future__ import annotations

from services.plant_ai_preview_row_builder import build_preview_contract_rows, field_rows


def test_row_builder_returns_plain_shared_preview_contract_rows() -> None:
    contract = build_preview_contract_rows(
        scope_category="mixed_scope_needs_routing",
        allowed_outputs=["design_intent", "company_handoff_draft", "safe_conceptual_summary"],
        blocked_outputs=["wet_lab_protocol", "primer_design"],
        boundary_statements=[
            "This preview is documentation-only.",
            "This preview is documentation-only.",
            "Manual review required.",
            "This preview does not generate final sequence.",
        ],
        parsed_intent_pairs=[
            ("Plant host", "rice"),
            ("Tissue/context", "seed"),
            ("Target", "albumin-like protein"),
            ("Handoff goal", "company-facing design evaluation package"),
        ],
        persistent=False,
    )

    assert contract["persistent"] is False
    assert contract["preview_status"] == "mixed input; safe fields only"
    assert contract["allowed_outputs"] == ["design_intent", "company_handoff_draft", "safe_conceptual_summary"]
    assert contract["blocked_outputs"] == ["wet_lab_protocol", "primer_design"]
    assert contract["boundary_statements"] == [
        "This preview is documentation-only.",
        "Manual review required.",
        "This preview does not generate completed sequence content.",
    ]
    assert contract["parsed_intent_rows"] == [
        {"Field": "Plant host", "Readback": "rice"},
        {"Field": "Tissue/context", "Readback": "seed"},
        {"Field": "Target", "Readback": "albumin-like protein"},
        {"Field": "Handoff goal", "Readback": "company-facing design evaluation package"},
    ]
    assert contract["allowed_output_rows"][0] == {
        "Output": "design intent",
        "Preview boundary": "visible only as documentation draft context",
    }
    assert contract["blocked_output_rows"] == [
        {"Output": "wet lab protocol", "Preview boundary": "blocked; not generated by this read-only preview"},
        {"Output": "primer design", "Preview boundary": "blocked; not generated by this read-only preview"},
    ]
    assert contract["boundary_statement_rows"] == [
        {"Boundary statement": "This preview is documentation-only."},
        {"Boundary statement": "Manual review required."},
        {"Boundary statement": "This preview does not generate completed sequence content."},
    ]


def test_field_rows_join_sequences_without_non_plain_types() -> None:
    rows = field_rows(
        [
            ("Uncertainty flags", ["species_context_missing", "evidence_review_pending"]),
            ("Manual review", True),
        ]
    )

    assert rows == [
        {"Field": "Uncertainty flags", "Readback": "species_context_missing, evidence_review_pending"},
        {"Field": "Manual review", "Readback": "True"},
    ]


def test_row_builder_flattens_nested_boundary_groups_for_presenter_reuse() -> None:
    contract = build_preview_contract_rows(
        scope_category="company_handoff_request",
        allowed_outputs=["company_handoff_draft"],
        blocked_outputs=["wet_lab_protocol"],
        boundary_statements=[
            ["This draft is not an experimental protocol.", "Manual expert review required."],
            ["This draft is not a final construct design."],
            "Read-only preview for manual review.",
        ],
        parsed_intent_pairs=[],
        persistent=False,
    )

    assert contract["boundary_statements"] == [
        "This draft is not an experimental protocol.",
        "Manual expert review required.",
        "This draft is not a final construct design.",
        "Read-only preview for manual review.",
    ]
