# -*- coding: utf-8 -*-
from __future__ import annotations

from services.plant_ai_user_input_mock_preview import build_user_input_mock_preview_payload


def _term(*parts: str) -> str:
    return "".join(parts)


FORBIDDEN_POSITIVE_TEXT = (
    _term("step", "-by-", "step"),
    _term("transformation ", "efficiency"),
    _term("success ", "guaran", "tee"),
    _term("synthesis", "-ready"),
    _term("wet lab ", "ready"),
    _term("culture ", "conditions"),
)


def _assert_plain_data(value: object) -> None:
    assert not hasattr(value, "__dataclass_fields__")
    if isinstance(value, dict):
        for key, nested in value.items():
            assert isinstance(key, str)
            _assert_plain_data(nested)
    elif isinstance(value, list):
        for nested in value:
            _assert_plain_data(nested)
    else:
        assert value is None or isinstance(value, (str, int, float, bool))


def _text(payload: dict[str, object]) -> str:
    return str(payload).casefold()


def test_user_input_mock_preview_supports_rice_albumin_like_input() -> None:
    payload = build_user_input_mock_preview_payload(
        "Prepare a company handoff draft for an albumin-like protein in rice seed."
    )

    assert payload["batch"] == "v2.7-r108"
    assert payload["read_only_preview"] is True
    assert payload["persistent"] is False
    assert payload["scope_category"] == "company_handoff_request"
    assert payload["preview_status"] == "supported plant mock preview"
    assert payload["allowed_outputs"][0] == "design_intent"
    assert payload["blocked_outputs"][-1] == "wet_lab_readiness_claim"
    assert payload["boundary_statements"]
    assert payload["workflow_route"] == "Supported plant review mock preview."
    assert any(row["Readback"] == "rice" for row in payload["parsed_intent_rows"])
    assert any(row["Readback"] == "seed" for row in payload["parsed_intent_rows"])
    assert any(row["Readback"] == "albumin-like protein" for row in payload["parsed_intent_rows"])
    assert payload["missing_information_rows"]
    assert payload["review_gap_rows"]


def test_user_input_mock_preview_blocks_wet_lab_or_final_design_input() -> None:
    payload = build_user_input_mock_preview_payload(
        "Give me a rice transformation protocol with cloning steps and primer design."
    )

    assert payload["scope_category"] == "mixed_scope_needs_routing"
    assert payload["preview_status"] == "mixed input; safe fields only"
    blocked = {row["Output"] for row in payload["blocked_output_rows"]}
    assert "wet lab protocol" in blocked
    assert "primer design" in blocked
    assert "final construct recommendation" in blocked
    assert {row["Preview boundary"] for row in payload["blocked_output_rows"]} == {
        "blocked; not generated by this read-only preview"
    }
    assert any(row["Review item"] == "blocked request fragment" for row in payload["review_gap_rows"])


def test_user_input_mock_preview_routes_non_plant_input_out_of_plant_workflow() -> None:
    payload = build_user_input_mock_preview_payload("Build a yeast expression workflow for a protein.")

    assert payload["scope_category"] == "non_plant_out_of_scope"
    assert payload["preview_status"] == "non-plant input routed out"
    assert payload["workflow_route"].startswith("Route out of Plant Design Workspace")
    assert payload["parsed_intent_rows"] == []
    assert payload["missing_information_rows"] == []
    assert payload["route_out_rows"]


def test_user_input_mock_preview_returns_plain_safe_payload() -> None:
    payload = build_user_input_mock_preview_payload(
        "Prepare a company handoff draft for rice seed albumin-like expression and include cloning protocol steps."
    )
    generated_preview = dict(payload)
    generated_preview["blocked_output_rows"] = []
    text = _text(generated_preview)

    _assert_plain_data(payload)
    assert "ai services" in text
    assert "persistence" in text
    assert "none" in text
    for phrase in FORBIDDEN_POSITIVE_TEXT:
        assert phrase not in text
