# -*- coding: utf-8 -*-
from __future__ import annotations

from services.plant_ai_handoff_preview_presenter import build_rice_albumin_handoff_preview_payload
from services.plant_ai_preview_row_builder import build_preview_contract_rows


def _term(*parts: str) -> str:
    return "".join(parts)


FORBIDDEN_OPERATIONAL_PHRASES = (
    _term("wet-lab ", "protocol"),
    _term("primer ", "sequence"),
    _term("final ", "sequence"),
    _term("synthesis", "-ready"),
    _term("transformation ", "efficiency"),
    _term("yield ", "prediction"),
    _term("guaran", "teed"),
    _term("valid", "ated"),
    _term("wet lab ", "ready"),
    _term("culture ", "conditions"),
    _term("cloning ", "steps"),
)


def _payload_text_without_allowed_negative_boundary(value: object) -> str:
    return str(value).casefold().replace("not an experimental protocol", "")


def test_presenter_returns_readable_payload_from_r102_draft() -> None:
    payload = build_rice_albumin_handoff_preview_payload()

    assert payload["title"] == "AI-guided Plant Design Handoff Preview"
    assert "deterministic fixture" in payload["subtitle"]
    assert payload["batch"] == "v2.7-r113"
    assert payload["read_only"] is True
    assert payload["persistent"] is False
    assert payload["preview_status"] == "supported plant mock preview"
    assert payload["status_badges"][0] == {
        "label": "Preview status",
        "value": "supported plant mock preview",
        "tone": "neutral",
    }
    assert payload["empty_state"]["is_empty"] is False
    assert payload["source_request"].startswith("I want to express an albumin-like protein")
    assert len(payload["handoff_section_rows"]) == 12
    assert {row["Title"] for row in payload["handoff_section_rows"]} >= {
        "Original User Request",
        "Parsed Design Intent",
        "Plant Design Context",
        "Construct Draft Slot Scaffold",
        "Boundary Statement",
    }


def test_presenter_payload_includes_rice_seed_albumin_company_context() -> None:
    payload = build_rice_albumin_handoff_preview_payload()
    text = str(
        [
            payload["request_scope_rows"],
            payload["parsed_intent_rows"],
            payload["design_intent_rows"],
            payload["plant_context_rows"],
        ]
    ).casefold()

    assert "rice" in text
    assert "seed" in text
    assert "albumin-like" in text
    assert "company-facing design evaluation package" in text
    assert "company handoff request" in text


def test_presenter_payload_includes_manual_review_boundary_and_gaps() -> None:
    payload = build_rice_albumin_handoff_preview_payload()
    text = str(payload).casefold()

    assert "manual review" in text
    assert "documentation-only" in text
    assert "non-operational" in text
    assert "draft slots only" in text
    assert "cds/source/version" in text
    assert "vector/backbone context" in text
    assert payload["manual_review_status_rows"]
    assert payload["missing_information_rows"]
    assert payload["review_gap_rows"]


def test_presenter_payload_splits_allowed_and_blocked_outputs() -> None:
    payload = build_rice_albumin_handoff_preview_payload()

    assert payload["allowed_outputs"][0] == "design_intent"
    assert payload["blocked_outputs"][-1] == "wet_lab_readiness_claim"
    allowed = {row["Output"] for row in payload["allowed_output_rows"]}
    blocked = {row["Output"] for row in payload["blocked_output_rows"]}
    boundaries = {row["Preview boundary"] for row in payload["allowed_output_rows"] + payload["blocked_output_rows"]}

    assert "design intent" in allowed
    assert "company handoff draft" in allowed
    assert "primer design" in blocked
    assert "yield prediction" in blocked
    assert "final construct recommendation" in blocked
    assert "visible only as documentation draft context" in boundaries
    assert "blocked; not generated by this read-only preview" in boundaries


def test_presenter_reuses_shared_preview_contract_row_builder() -> None:
    payload = build_rice_albumin_handoff_preview_payload()
    shared_contract = build_preview_contract_rows(
        scope_category=payload["scope_category"],
        allowed_outputs=payload["allowed_outputs"],
        blocked_outputs=payload["blocked_outputs"],
        boundary_statements=payload["boundary_statements"],
        parsed_intent_pairs=[
            ("Plant host", "rice"),
            ("Tissue/context", "seed"),
            ("Target", "albumin-like protein"),
            ("Handoff goal", "company-facing design evaluation package"),
        ],
        persistent=payload["persistent"],
        allowed_output_boundary_label="visible only as documentation draft context",
    )

    assert payload["preview_status"] == shared_contract["preview_status"]
    assert payload["allowed_outputs"] == shared_contract["allowed_outputs"]
    assert payload["blocked_outputs"] == shared_contract["blocked_outputs"]
    assert payload["boundary_statements"] == shared_contract["boundary_statements"]
    assert payload["parsed_intent_rows"] == shared_contract["parsed_intent_rows"]
    assert payload["persistent"] is shared_contract["persistent"]
    assert payload["allowed_output_rows"] == shared_contract["allowed_output_rows"]
    assert payload["blocked_output_rows"] == shared_contract["blocked_output_rows"]
    assert payload["boundary_statement_rows"] == shared_contract["boundary_statement_rows"]


def test_presenter_payload_does_not_emit_forbidden_positive_or_operational_content() -> None:
    payload = build_rice_albumin_handoff_preview_payload()
    generated_preview = dict(payload)
    generated_preview["blocked_output_rows"] = []
    text = _payload_text_without_allowed_negative_boundary(generated_preview)

    for phrase in FORBIDDEN_OPERATIONAL_PHRASES:
        assert phrase not in text


def test_presenter_empty_state_is_safe_for_invalid_handoff_draft() -> None:
    payload = build_rice_albumin_handoff_preview_payload(domain_bundle={}, handoff_draft={})

    assert payload["empty_state"]["is_empty"] is True
    assert payload["read_only"] is True
    assert "unavailable" in payload["empty_state"]["message"]
    assert payload["allowed_output_rows"] == []
    assert payload["blocked_output_rows"] == []
